language: php
cache:
  directories:
  - $HOME/.composer/cache

jobs:
  include:
  - stage: upload to TER
    if: tag IS present
    php: 7.0
    script:
    - >
      if [ -n "$TYPO3_ORG_USERNAME" ] && [ -n "$TYPO3_ORG_PASSWORD" ]; then
        echo -e "Preparing upload of release ${TRAVIS_TAG} to TER\n";
        # Install ter client
        composer global require helhum/ter-client

        # Upload
        TAG_MESSAGE=`git tag -n10 -l $TRAVIS_TAG | sed 's/^[0-9.]*[ ]*//g'`
        echo "Uploading release ${TRAVIS_TAG} to TER"
        $HOME/.composer/vendor/bin/ter-client upload typo3_console . -u "$TYPO3_ORG_USERNAME" -p "$TYPO3_ORG_PASSWORD" -m "$TAG_MESSAGE"
      fi;
