services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Hoogi91\AccessRestriction\:
    resource: '../Classes/*'

  Hoogi91\AccessRestriction\Hook\DataHandler:
    public: true