name: "Static analysis"

on:
  pull_request:
  push:

jobs:
  static-analysis:
    name: "Static analysis"

    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        dependencies:
          - "locked"
        php-version:
          - "8.1"
        operating-system:
          - "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Composer install"
        uses: ./.github/actions/composer
        with:
          php-version: '${{ matrix.php-version }}'
          dependencies: '${{ matrix.dependencies }}'
          extensions: json, mbstring

      - name: "PHPStan"
        run: .Build/bin/phpstan analyse --level 5 Classes/